"""empty message

Revision ID: a755ba48614d
Revises: d2045fbf7929
Create Date: 2024-06-25 17:38:23.693945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a755ba48614d'
down_revision = 'd2045fbf7929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), server_default='', nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), server_default=sa.text("('')"), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
